### ISSUE TITLE
Any examples on real human picture rather than gan generated one?

### ISSUE THREAD

**Issue by lucasjinreal** [johnGettings/LIHQ#1]
it looks like gan generated picture are obviously faked.

**Comment by johnGettings** [comment]
Check out the deepfake example video. https://m.youtube.com/watch?v=nPAV-jpTzqI

Though I think the stylgan2 faces look best. I don't think real people will look more realistic. 

Check out the examples colab. It has an example of cropping and aligning a picture of a real person.
