### ISSUE TITLE
ModuleNotFoundError: No module named 'LIHQ.QVI.demo'

### ISSUE THREAD

**Issue by nexus-collab** [johnGettings/LIHQ#2]
I get this error every time I try to run the collab

**Comment by johnGettings** [comment]
On which cell do you get this error?

**Comment by johnGettings** [comment]
Okay I found it.
It looks like gdown has a bug in it that wasn't allowing me to download demo.py. I upgraded to the latest version in requirements.txt and it seems to be working for me now.

**Comment by nexus-collab** [comment]
It is running now but still get an error every time (attached screenshot),
it says video complete but when I go to that folder it is just some example
footage not my footage
[image: image.png]
_____________________
Sincerely,
Corey Wade
323.739.7664

**Comment by johnGettings** [comment]
I'm not seeing the image

**Comment by johnGettings** [comment]
There are a lot of options within the primary LIHQ colab but if you look at the 'Examples' colab you'll find it can be pretty simple as well.
All you need is audio file(s) in the audio folder, a cropped image of a face (specify location with the 'face' argument in run.py) , click run and find the video output in: LIHQ ->output -> finalVidsOut

If you complete those three steps it should work, as long as the audio is clean and the face is within specifications mentioned in the colab. Everything else is optional.

**Comment by nexus-collab** [comment]
The issue is it completes all frames but when it tries to generate a video
it crashes and disconnects, deleting everything I have uploaded as well as
any outputs, happens every time. I brought image size down to 512x512,
still doesn't work
_____________________
Sincerely,
Corey Wade
323.739.7664

**Comment by johnGettings** [comment]
Face image size shouldn't matter too much.

What is the length of your audio? As it states in the name, the tool has a LONG inference time and uses a couple models that requires high RAM use. This tool is not really meant to create a 15 minute video. I would recommend keeping audio clips to under 30 seconds and splicing together finished video clips as necessary. Be sure to look at 'ref_vid_offset' argument if you want the spliced clips to look seamless.

If you are still running out of memory go into colab settings: Runtime -> Change Runtime Type -> select high-RAM option.
I have tested on a T4 and have never received OOM, so check your GPU and see if it is anything less powerful than that. It may be a problem. You can subscribe to google colab+ and get more RAM, better GPUs, more frequently.
